const userActionTypes = {
    REQUEST_AUTHENTIFICATION_LOGOUT: "REQUEST_AUTHENTIFICATION_LOGOUT",
    REQUEST_AUTHENTICATION_START: "REQUEST_AUTHENTICATION_START",
    REQUEST_AUTHENTICATION_SUCCESS: "REQUEST_AUTHENTICATION_SUCCESS",
    REQUEST_AUTHENTICATION_FAILURE: "REQUEST_AUTHENTICATION_FAILURE",
};

export default userActionTypes;