
export const certificateType = {
    "LOADING_CERTIFICATE": "LOADING_CERTIFICATE",
    "SUCCESS_DOWNLOAD_CERTIFICATE": "SUCCESS_DOWNLOAD_CERTIFICATE",
    "ERROR_DOWNLOAD_CERTIFICATE": "ERROR_DOWNLOAD_CERTIFICATE"
};